version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily" # 動作確認したらmonthlyに変える
      time: "11:10"
      timezone: "Asia/Tokyo"
    # ignore:
    #   - dependency-name: "*"
    #     update-types: ["version-update:semver-minor", "version-update:semver-patch"]
